#!/usr/bin/env python3
"""Generate the Heliostat launcher icon from ONE geometry.

Writes the adaptive-icon layers (vector drawables) and the legacy bitmaps for
Android 7.x, which predates adaptive icons. Run from the repo root:

    python3 tools/make_icon.py

The picture: a sun, a mirror on its stand, and the reflected beam landing in a
target ring -- the same story the app's sky dial tells, in the app's palette.
Coordinates are in the 108x108 adaptive-icon viewport; everything is scaled by
SCALE about the centre so it sits inside the 66 dp safe zone every launcher
mask (circle, squircle, rounded square) leaves visible.
"""

import math
from pathlib import Path

from PIL import Image, ImageDraw

RES = Path(__file__).resolve().parent.parent / "app" / "src" / "main" / "res"
SCALE = 0.9

NAVY = "#0B1220"
NAVY_2 = "#17223A"
AMBER = "#FFB84D"
SILVER = "#DDE3F0"
STAND = "#6F7A91"
CORAL = "#FF8A65"
SKY = "#8FCBFF"

SUN = (40.0, 40.0, 9.0)                # centre x, y, radius
# Seven rays: the one pointing at the mirror (45 deg, down-right) is left out,
# so the beam leaving the sun is not confused with a ray.
RAYS = [(40 + r0 * math.cos(a), 40 + r0 * math.sin(a), 40 + r1 * math.cos(a), 40 + r1 * math.sin(a))
        for a in (k * math.pi / 4 for k in range(8) if k != 1) for r0, r1 in [(12.5, 16.0)]]
MIRROR = (49.1, 65.6, 74.9, 68.4)      # the reflective face: nearly level, tilted ~6 deg
STAND_POST = (62.0, 69.0, 62.0, 80.0)
STAND_BASE = (55.0, 80.0, 69.0, 80.0)
_HIT = (61.5, 65.5)                    # where the beam meets the mirror
_DIR = math.atan2(_HIT[1] - 40, _HIT[0] - 40)
BEAM_IN = (40 + 11.5 * math.cos(_DIR), 40 + 11.5 * math.sin(_DIR), *_HIT)  # sun's edge -> mirror
BEAM_OUT = (62.5, 65.5, 82.0, 49.5)    # mirror -> target
TARGET = (85.5, 46.5, 4.0)


# --- vector drawables ----------------------------------------------------------------

def circle_path(cx, cy, r):
    return f"M{cx - r:.2f},{cy:.2f} a{r:.2f},{r:.2f} 0 1,0 {2 * r:.2f},0 a{r:.2f},{r:.2f} 0 1,0 {-2 * r:.2f},0 Z"


def line_path(x1, y1, x2, y2):
    return f"M{x1:.2f},{y1:.2f} L{x2:.2f},{y2:.2f}"


def stroke(path, color, width):
    return (f'        <path android:pathData="{path}" android:strokeColor="{color}" '
            f'android:strokeWidth="{width}" android:strokeLineCap="round" />')


def fill(path, color):
    return f'        <path android:pathData="{path}" android:fillColor="{color}" />'


def foreground_xml(mono=False):
    c = (lambda color: "#FFFFFFFF") if mono else (lambda color: color)
    shapes = [
        fill(circle_path(*SUN), c(AMBER)),
        *[stroke(line_path(*ray), c(AMBER), 2.4) for ray in RAYS],
        stroke(line_path(*BEAM_IN), c(CORAL), 2.2),
        stroke(line_path(*BEAM_OUT), c(CORAL), 2.2),
        stroke(line_path(*STAND_POST), c(STAND), 2.4),
        stroke(line_path(*STAND_BASE), c(STAND), 2.4),
        stroke(line_path(*MIRROR), c(SILVER), 4.6),
        stroke(circle_path(*TARGET), c(SKY), 2.0),
    ]
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Generated by tools/make_icon.py. Edit the script, not this file. -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="108dp" android:height="108dp"\n'
        '    android:viewportWidth="108" android:viewportHeight="108">\n'
        f'    <group android:pivotX="54" android:pivotY="54" android:scaleX="{SCALE}" android:scaleY="{SCALE}">\n'
        + "\n".join(shapes)
        + "\n    </group>\n</vector>\n"
    )


def background_xml():
    # A faint lighter disc behind the scene: night sky with a little depth.
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Generated by tools/make_icon.py. Edit the script, not this file. -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="108dp" android:height="108dp"\n'
        '    android:viewportWidth="108" android:viewportHeight="108">\n'
        f'    <path android:pathData="M0,0 H108 V108 H0 Z" android:fillColor="{NAVY}" />\n'
        f'    <path android:pathData="{circle_path(54, 54, 40)}" android:fillColor="{NAVY_2}" />\n'
        "</vector>\n"
    )


# --- legacy bitmaps (Android 7.x) -------------------------------------------------------

def render(size, round_mask):
    ss = 4  # supersample, then downscale for smooth edges
    big = size * ss
    unit = big / 108.0

    def p(x, y):  # icon space -> pixels, with the same centred scale as the vector
        return ((54 + SCALE * (x - 54)) * unit, (54 + SCALE * (y - 54)) * unit)

    def w(width):
        return max(1, int(round(width * SCALE * unit)))

    img = Image.new("RGBA", (big, big), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    # Legacy icons are drawn full-bleed on their own shape.
    if round_mask:
        d.ellipse([0, 0, big - 1, big - 1], fill=NAVY)
    else:
        d.rounded_rectangle([0, 0, big - 1, big - 1], radius=int(big * 0.22), fill=NAVY)
    r = 40 * unit
    d.ellipse([54 * unit - r, 54 * unit - r, 54 * unit + r, 54 * unit + r], fill=NAVY_2)

    def line(seg, color, width):
        a, b = p(seg[0], seg[1]), p(seg[2], seg[3])
        d.line([a, b], fill=color, width=w(width))
        rad = w(width) / 2
        for x, y in (a, b):  # round caps
            d.ellipse([x - rad, y - rad, x + rad, y + rad], fill=color)

    def ring(cx, cy, radius, color, width):
        (x, y), rr = p(cx, cy), radius * SCALE * unit
        d.ellipse([x - rr, y - rr, x + rr, y + rr], outline=color, width=w(width))

    (x, y), rr = p(SUN[0], SUN[1]), SUN[2] * SCALE * unit
    d.ellipse([x - rr, y - rr, x + rr, y + rr], fill=AMBER)
    for ray in RAYS:
        line(ray, AMBER, 2.4)
    line(BEAM_IN, CORAL, 2.2)
    line(BEAM_OUT, CORAL, 2.2)
    line(STAND_POST, STAND, 2.4)
    line(STAND_BASE, STAND, 2.4)
    line(MIRROR, SILVER, 4.6)
    ring(*TARGET, SKY, 2.0)
    return img.resize((size, size), Image.LANCZOS)


def main():
    (RES / "drawable" / "ic_launcher_foreground.xml").write_text(foreground_xml())
    (RES / "drawable" / "ic_launcher_monochrome.xml").write_text(foreground_xml(mono=True))
    (RES / "drawable" / "ic_launcher_background.xml").write_text(background_xml())
    for name in ("ic_launcher.xml", "ic_launcher_round.xml"):
        (RES / "mipmap-anydpi-v26" / name).write_text(
            '<?xml version="1.0" encoding="utf-8"?>\n'
            '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
            '    <background android:drawable="@drawable/ic_launcher_background" />\n'
            '    <foreground android:drawable="@drawable/ic_launcher_foreground" />\n'
            '    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />\n'
            "</adaptive-icon>\n"
        )
    for density, size in {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}.items():
        folder = RES / f"mipmap-{density}"
        render(size, round_mask=False).save(folder / "ic_launcher.webp", "WEBP", lossless=True)
        render(size, round_mask=True).save(folder / "ic_launcher_round.webp", "WEBP", lossless=True)
    # A large preview, for looking at the design.
    render(512, round_mask=False).save("/tmp/claude-1000/icon_preview.png")
    render(512, round_mask=True).save("/tmp/claude-1000/icon_preview_round.png")
    print("icon written")


if __name__ == "__main__":
    main()
